Ignore paths
jasonolmstead33/ctrace-go pull request #1
Opened 2017-07-26 15:35 UTC by jasonolmstead33

Adding functionality to allow ignored paths in the HTTPTracer

2017-07-26 16:44 UTC, andyday requested changes

2017-07-26 16:44 UTC, andyday commented on http.go
> +	ignoredPaths *regexp.Regexp,
actually we should use the interceptor for this.  you can add an ignore field to the SpanConfig and set that however you want in the interceptor.

2017-08-03 04:46 UTC, andyday requested changes

2017-08-03 04:46 UTC, andyday commented on http.go
> +			h.ServeHTTP(w, r)
add a return after this and then you can remove the else below and reduce nesting...

2017-08-03 04:46 UTC, andyday commented on http.go
> +				ignored = config.IgnoredPaths.MatchString(r.URL.String())
you can remove the ignored var and do

```js
if config.IgnoredPaths != null {
  if config.IgnoredPaths.MatchString(r.URL.String()) {
    h.ServeHTTP(w, r)
    return
  }
}
```

2017-08-03 04:46 UTC, andyday commented on span_config.go
> +	IgnoredPaths *regexp.Regexp
Since this is a single expression i would change the name to `Ignore`

2017-08-03 14:50 UTC, jasonolmstead33 commented
@andyday check it out now. I can close this and make the PR into HEAD if you like it.

2017-08-03 15:19 UTC, andyday commented
looks good.  you can open the same pr into HEAD.

2017-08-03 15:35 UTC, merged